### ISSUE TITLE
Usage is Wrong

### ISSUE THREAD

**Issue by redreceipt** [severoraz/todo.txt_cli-setdue#1]
Usage is outputting the `$self` variable incorrectly, not sure how to fix myself or I would give it a try.

https://github.com/severoraz/todo.txt_cli-setdue/blob/934cd46fb29ef75d7771c849f76682c70ddf8f2b/setdue#L169

![Screen Shot 2019-03-25 at 10 30 54 AM](https://user-images.githubusercontent.com/2659478/54927773-341a5c00-4ee9-11e9-815e-2b49b860f089.png)

**Comment by severoraz** [comment]
Thanks for reporting the bug. It should be fixed now. I'm not sure why I had tried to set the `self` variable dynamically, but now just replaced it by a string literal. Please let me know if this fixes the problem for you.
